### ISSUE TITLE
Investigation of design desigions

### ISSUE THREAD

**Issue by MaxymVlasov** [kubernetes-sigs/kube-network-policies#116]
Hi @aojea 
I recently found that NetworkPolicy fields are inconsistent in their behavior.
IE:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: foo
spec:
  podSelector: {} # <-- Allow All
  ingress: [] # <-- Deny All
```
but
```yaml
  ingress: [{}] # <-- Allow All ports
```

After some researching, I found that it was done not because of some weird YAML/JSON merge behavior, but set as defaults in the codebase, IE

https://github.com/kubernetes-sigs/kube-network-policies/blame/9fe16a155a7e116bdbd482d29e0dba6b6bb7ff3f/pkg/networkpolicy/controller.go#L754-L756

But this code was introduced by you just 7 months ago, when NetworkPolicies have existed for years, at least from 1.25

https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports

Could you please point me to where the codebase was located before it moved here? The original commit, sadly, does not contain any info about it.

I am trying to understand why such a decision was made in the first place, that now it requires https://editor.networkpolicy.io/ to work with it in a meaningful way.
