### ISSUE TITLE
[bug] Delay in enforcing NetworkPolicy rules

### ISSUE THREAD

**Issue by azych** [kubernetes-sigs/kube-network-policies#171]
**What's the problem?**

When running kind v0.27.0, which uses kindnet, which in turns uses kube-network-policies to handle NetworkPolicies, there is a delay in already existing networkpolicy rules being enforced for newly created pods. This also means that short-lived pods (eg. a pod that just runs a single command) are not being restricted at all.

**Steps to reproduce**

1. Create a default kind cluster using the latest release version:
```
kind --version
kind version 0.27.0
```
```
kind create cluster
```

2. Given a single existing NetworkPolicy that denies external egress:
```
kubectl get networkpolicy
NAME          POD-SELECTOR   AGE
deny-egress   app=backend    27m
```
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress
  namespace: default
spec:
  egress:
  - to:
    - namespaceSelector: {}
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Egress
```

3. And a properly labeled pod which makes repeated wget requests to external resource:
```
kubectl run lr --image=busybox --restart=Never --labels app=backend -- /bin/sh -c 'while true; do wget --no-check-certificate --timeout=2 https://github.com; sleep 10; done'
```

4. Logs show that the first request was not restricted:
```
kubectl logs lr -f
Connecting to github.com (140.82.121.4:443)
saving to 'index.html'
index.html           100% |********************************|  278k  0:00:00 ETA
'index.html' saved
Connecting to github.com (140.82.121.4:443)
wget: download timed out
Connecting to github.com (140.82.121.3:443)
wget: download timed out
```

A similar case happens for temporary pod run in interactive mode and with automatic cleanup enabled:
```
kubectl run tmp --rm -it --image=busybox --restart=Never --labels app=backend -- wget --no-check-certificate --timeout=2 https://github.com                                  
Connecting to github.com (140.82.121.4:443)
saving to 'index.html'
index.html           100% |********************************|  278k  0:00:00 ETA
'index.html' saved
pod "tmp" deleted
```

**What's the expected behavior?**

Networkpolicy rules are being enforced without delay/restrictions.
I verified this behavior with other CNIs (eg. calico) and there is no such issue.

Also, open to potentially work on/help with a fix.
